export const serviceCatalog = Object.freeze({
  "visa-extension-phuket": { fees: [["standardExtension", 1900], ["overstayDay", 500], ["overstayMaximum", 20000]], scope: ["caseReview", "documentChecklist", "tm30Check", "appointmentPreparation"] },
  "retirement-visa-phuket": { fees: [["retirementExtension", 1900], ["multipleReEntry", 3800]], scope: ["eligibilityCheck", "timelinePlan", "financialEvidence", "appointmentGuidance"] },
  "non-immigrant-visa-phuket": { fees: [["nonImmigrantExtension", 1900], ["multipleReEntry", 3800]], scope: ["categoryAssessment", "documentChecklist", "timelinePlan", "appointmentGuidance"] },
  "dtv-visa-phuket": { fees: [["dtvApplication", 10000], ["dtvExtension", 1900]], scope: ["categoryAssessment", "documentChecklist", "alternativeAssessment", "timelinePlan"] },
  "90-day-report-phuket": { fees: [["onTime90Day", "free"], ["late90Day", 2000]], scope: ["dueDateCheck", "formPreparation", "onlineOrOffice", "deadlinePlanning"] },
  "re-entry-permit-phuket": { fees: [["singleReEntry", 1000], ["multipleReEntry", 3800]], scope: ["permitSelection", "formPreparation", "documentChecklist", "departurePlanning"] },
  "thai-driving-license-phuket": { fees: [["temporaryCar", 205], ["temporaryMotorcycle", 105], ["carRenewal", 505]], scope: ["eligibilityCheck", "documentChecklist", "certificateGuidance", "dltPreparation"] },
  "tm30-phuket": { fees: [["onTimeTm30", "free"], ["lateTm30", [800, 2000]]], scope: ["statusCheck", "ownerCoordination", "filingUpdate", "appointmentPreparation"] }
});

export const serviceCopy = Object.freeze({
  en: {
    feesTitle: "Official government fees", feeType: "Fee type", amount: "Amount", agencyFee: "Our agency service fee", onRequest: "On request",
    feeNote: "Government fees are separate from our service fee and may change. We confirm the current amount before you proceed.", scopeTitle: "What our support includes",
    feeLabels: { standardExtension:"Standard visa extension (for example tourist, 30 days)",overstayDay:"Overstay fine per day",overstayMaximum:"Maximum overstay fine",retirementExtension:"One-year retirement extension",multipleReEntry:"Multiple re-entry permit",nonImmigrantExtension:"One-year extension (Non-O, Non-B or Non-ED)",dtvApplication:"DTV visa application at a Thai embassy",dtvExtension:"In-country DTV extension (180 days)",onTime90Day:"On-time 90-day report",late90Day:"Late filing fine",singleReEntry:"Single re-entry permit",temporaryCar:"Temporary car licence (2 years)",temporaryMotorcycle:"Temporary motorcycle licence (2 years)",carRenewal:"Car licence renewal (5 years)",onTimeTm30:"On-time TM30 notification",lateTm30:"Typical late-filing fine" },
    scopeLabels: { caseReview:"Visa type and case review",documentChecklist:"Personal document checklist",tm30Check:"TM30 status check",appointmentPreparation:"Appointment preparation",eligibilityCheck:"Eligibility check",timelinePlan:"Application timeline planning",financialEvidence:"Bank and financial evidence guidance",appointmentGuidance:"Immigration appointment guidance",categoryAssessment:"Suitable visa or category assessment",alternativeAssessment:"Comparison with realistic alternatives",dueDateCheck:"Due-date check",formPreparation:"Form preparation",onlineOrOffice:"Online or in-person filing guidance",deadlinePlanning:"Deadline and compliance planning",permitSelection:"Single or multiple permit selection",departurePlanning:"Planning before departure",certificateGuidance:"Residence and medical certificate guidance",dltPreparation:"DLT process and test preparation",statusCheck:"Existing filing and status check",ownerCoordination:"Owner or landlord coordination",filingUpdate:"Filing or update guidance" }
  },
  de: {
    feesTitle:"Offizielle Behördengebühren",feeType:"Gebührenart",amount:"Betrag",agencyFee:"Unsere Servicegebühr",onRequest:"Auf Anfrage",feeNote:"Behördengebühren sind von unserer Servicegebühr getrennt und können sich ändern. Wir bestätigen den aktuellen Betrag vor Beginn.",scopeTitle:"Das umfasst unsere Unterstützung",
    feeLabels:{standardExtension:"Standard-Visumverlängerung (z. B. Touristenvisum, 30 Tage)",overstayDay:"Overstay-Strafe pro Tag",overstayMaximum:"Maximale Overstay-Strafe",retirementExtension:"Einjährige Retirement-Verlängerung",multipleReEntry:"Multiple Re-Entry Permit",nonImmigrantExtension:"Einjährige Verlängerung (Non-O, Non-B oder Non-ED)",dtvApplication:"DTV-Antrag bei einer thailändischen Botschaft",dtvExtension:"DTV-Verlängerung im Land (180 Tage)",onTime90Day:"Fristgerechte 90-Tage-Meldung",late90Day:"Strafe für verspätete Meldung",singleReEntry:"Single Re-Entry Permit",temporaryCar:"Vorläufiger Autoführerschein (2 Jahre)",temporaryMotorcycle:"Vorläufiger Motorradführerschein (2 Jahre)",carRenewal:"Autoführerschein-Verlängerung (5 Jahre)",onTimeTm30:"Fristgerechte TM30-Meldung",lateTm30:"Übliche Strafe bei verspäteter Meldung"},
    scopeLabels:{caseReview:"Prüfung von Visumtyp und Situation",documentChecklist:"Persönliche Dokumentencheckliste",tm30Check:"Prüfung des TM30-Status",appointmentPreparation:"Vorbereitung auf den Termin",eligibilityCheck:"Prüfung der Voraussetzungen",timelinePlan:"Planung des Antragsablaufs",financialEvidence:"Unterstützung bei Bank- und Finanznachweisen",appointmentGuidance:"Begleitung des Immigration-Termins",categoryAssessment:"Prüfung der passenden Visa-Kategorie",alternativeAssessment:"Vergleich mit realistischen Alternativen",dueDateCheck:"Prüfung des Fälligkeitstermins",formPreparation:"Vorbereitung der Formulare",onlineOrOffice:"Hilfe bei Online- oder Vor-Ort-Meldung",deadlinePlanning:"Fristen- und Compliance-Planung",permitSelection:"Auswahl Single oder Multiple Permit",departurePlanning:"Planung vor der Ausreise",certificateGuidance:"Hilfe bei Wohnsitz- und Gesundheitsbescheinigung",dltPreparation:"Vorbereitung auf DLT-Ablauf und Tests",statusCheck:"Prüfung bestehender Meldung und Status",ownerCoordination:"Abstimmung mit Eigentümer oder Vermieter",filingUpdate:"Unterstützung bei Einreichung oder Aktualisierung"}
  },
  ru: {
    feesTitle:"Официальные государственные пошлины",feeType:"Вид сбора",amount:"Сумма",agencyFee:"Сервисный сбор агентства",onRequest:"По запросу",feeNote:"Государственные сборы оплачиваются отдельно от наших услуг и могут меняться. Мы подтвердим актуальную сумму до начала процесса.",scopeTitle:"Что входит в нашу поддержку",
    feeLabels:{standardExtension:"Стандартное продление визы (например, туристической на 30 дней)",overstayDay:"Штраф за оверстей за день",overstayMaximum:"Максимальный штраф за оверстей",retirementExtension:"Продление пенсионного пребывания на один год",multipleReEntry:"Многократное разрешение на повторный въезд",nonImmigrantExtension:"Продление на один год (Non-O, Non-B или Non-ED)",dtvApplication:"Подача на DTV в посольстве Таиланда",dtvExtension:"Продление DTV в Таиланде (180 дней)",onTime90Day:"Своевременный 90-дневный отчёт",late90Day:"Штраф за просрочку",singleReEntry:"Однократное разрешение на повторный въезд",temporaryCar:"Временные права на автомобиль (2 года)",temporaryMotorcycle:"Временные права на мотоцикл (2 года)",carRenewal:"Продление автомобильных прав (5 лет)",onTimeTm30:"Своевременное уведомление TM30",lateTm30:"Обычный штраф за позднюю подачу"},
    scopeLabels:{caseReview:"Проверка типа визы и ситуации",documentChecklist:"Персональный список документов",tm30Check:"Проверка статуса TM30",appointmentPreparation:"Подготовка к визиту",eligibilityCheck:"Проверка соответствия требованиям",timelinePlan:"Планирование процесса подачи",financialEvidence:"Подготовка банковских и финансовых подтверждений",appointmentGuidance:"Сопровождение визита в иммиграцию",categoryAssessment:"Подбор подходящей категории визы",alternativeAssessment:"Сравнение с реалистичными альтернативами",dueDateCheck:"Проверка срока подачи",formPreparation:"Подготовка форм",onlineOrOffice:"Помощь с онлайн-подачей или визитом",deadlinePlanning:"Планирование сроков и соблюдения правил",permitSelection:"Выбор однократного или многократного разрешения",departurePlanning:"Планирование до выезда",certificateGuidance:"Помощь со справкой о месте жительства и медсправкой",dltPreparation:"Подготовка к процедуре и тестам DLT",statusCheck:"Проверка существующей регистрации и статуса",ownerCoordination:"Координация с владельцем или арендодателем",filingUpdate:"Помощь с подачей или обновлением"}
  }
});
